services:
  bead:
    container_name: bead
    build: .
    tty: true
    stdin_open: true
    volumes:
      - ./:/bead-framework
    working_dir: /bead-framework
    user: bead
    environment:
      PHP_IDE_CONFIG: "serverName=BeadFramework"
      XDEBUG_CONFIG: "client_host=xdebug-client"
    extra_hosts:
      - "xdebug-client:host-gateway"
