name: Coding standards

on:
  push:
    branches: ["production"]
  pull_request:
    branches: ["production"]

jobs:
  coding-standards:
    name: Coding Standards
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        directory:
          - "src"
          - "standards"
          - "test"

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Start PHP 8.1 docker container
        run: |
          docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERTOKEN }}
          docker compose up -d bead-8.1

      - name: Install composer dependencies
        run: |
          rm -rf vendor
          chmod ugo+rw .
          docker exec bead-8.1 composer update

      - name: Run phpcs
        run: |
          docker exec -u root bead-8.1 rm -f /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
          docker exec bead-8.1 ./vendor/bin/phpcs "${{ matrix.directory }}/"
