name: PHP 8.1 unit tests

on:
  push:
    branches: ["production"]
  pull_request:
    branches: ["production"]

jobs:
  run-tests:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Install PHP 8.1 and extensions
        run: |
          sudo add-apt-repository -y ppa:ondrej/php
          sudo apt-get update
          sudo apt-get -y install php8.1-cli php8.1-curl php8.1-dom php8.1-mbstring php8.1-uopz

      - name: Select PHP 8.1
        run: sudo update-alternatives --set php /usr/bin/php8.1

      - name: Configure PHP 8.1 for development environment
        run: sudo cp /usr/lib/php/8.1/php.ini-development /etc/php/8.1/cli/php.ini

      - name: Install composer dependencies
        run: |
          rm composer.lock
          rm -rf vendor
          composer install

      - name: Run unit tests
        run: ./vendor/bin/phpunit --configuration ./test/phpunit.xml --testsuite 'bead-framework Full Test Suite' --do-not-cache-result ./test
