name: PHP unit tests

on:
  push:
    branches: ["production"]
  pull_request:
    branches: ["production"]

jobs:
  run-tests:
    name: Run unit tests
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        php_version:
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Start PHP ${{ matrix.php_version }} docker container
        run: |
          docker login -u ${{ secrets.DOCKERUSERNAME }} -p ${{ secrets.DOCKERTOKEN }}
          docker compose up -d bead-${{ matrix.php_version }}

      - name: Install composer dependencies
        run: |
          rm composer.lock
          rm -rf vendor
          docker exec bead-${{ matrix.php_version }} composer install

      - name: Run unit tests
        run: docker exec bead-${{ matrix.php_version }} ./vendor/bin/phpunit --configuration ./test/phpunit.xml --testsuite 'bead-framework Full Test Suite' --do-not-cache-result ./test
