name: PHP 8.0 unit tests

on:
  push:
    branches: ["production"]
  pull_request:
    branches: ["production"]

jobs:
  run-tests:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install PHP versions and extensions
        run: |
          sudo add-apt-repository -y ppa:ondrej/php
          sudo apt-get update
          sudo apt-get -y upgrade
          sudo apt-get -y install php8.0 php8.0-dom php8.0-mbstring php8.0-uopz

      - name: Select PHP 8.0
        run: sudo update-alternatives --set php /usr/bin/php8.0

      - name: Install composer dependencies
          rm composer.lock
          rm -rf vendor
          composer install

      - name: Run unit tests
          ./vendor/bin/phpunit --configuration ./test/phpunit.xml --testsuite 'bead-framework Full Test Suite' --do-not-cache-result ./test
