name: Run unit tests

on:
  push:
    branches: ["production"]
  pull_request:
    branches: ["production"]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # ensure uopz extension is installed
      - name: Install PHP versions and extensions
        run: |
          sudo add-apt-repository -y ppa:ondrej/php
          sudo apt-get update
          sudo apt-get -y upgrade
          sudo apt-get -y install php7.4 php8.0 php8.1 php7.4-uopz php8.0-uopz php8.1-uopz

      - name: Install composer dependencies for PHP7.4
        run: |
          rm -rf vendor
          /usr/bin/php7.4 composer install

      - name: Run PHPUnit for PHP7.4
        run: /usr/bin/php7.4 ./vendor/bin/phpunit --configuration ./test/phpunit.xml --testsuite 'bead-framework Full Test Suite' --do-not-cache-result ./test

      - name: Install composer dependencies for PHP8.0
        run: |
          rm -rf vendor
          /usr/bin/php8.0 composer install

      - name: Run PHPUnit for PHP8.0
        run: /usr/bin/php8.0 ./vendor/bin/phpunit --configuration ./test/phpunit.xml --testsuite 'bead-framework Full Test Suite' --do-not-cache-result ./test

      - name: Install composer dependencies for PHP8.1
        run: |
          rm -rf vendor
          /usr/bin/php8.1 composer install

      - name: Run PHPUnit for PHP8.1
        run: /usr/bin/php8.1 ./vendor/bin/phpunit --configuration ./test/phpunit.xml --testsuite 'bead-framework Full Test Suite' --do-not-cache-result ./test
